[env:nucleo_h723zg]
platform = ststm32
board = nucleo_h723zg
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit BMP3XX Library @ ^2.1.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
